server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: api-gateway

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    public-paths: /api/v1/auth, /actuator/health, /api/docs, /swagger-ui, /v3/api-docs, /swagger-docs/auth, /swagger-docs/org

management:
  endpoints:
    web:
      exposure:
        include: health, metrics

logging:
  level:
    root: INFO
    in.respondlyai: DEBUG
    org.springframework.cloud.gateway: DEBUG

springdoc:
  swagger-ui:
    path: /api/docs
    urls:
      - name: Auth API
        url: /swagger-docs/auth
      - name: Organization API
        url: /swagger-docs/org
